// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckControlVectors(arg1) {
  return window['go']['main']['App']['CheckControlVectors'](arg1);
}

export function DefineControlVector(arg1, arg2) {
  return window['go']['main']['App']['DefineControlVector'](arg1, arg2);
}

export function GetDemo() {
  return window['go']['main']['App']['GetDemo']();
}

export function GetPlayerPosition(arg1) {
  return window['go']['main']['App']['GetPlayerPosition'](arg1);
}

export function GetPlayers(arg1) {
  return window['go']['main']['App']['GetPlayers'](arg1);
}

export function GetRayCast(arg1) {
  return window['go']['main']['App']['GetRayCast'](arg1);
}

export function GetTickCount() {
  return window['go']['main']['App']['GetTickCount']();
}

export function GetTicksOfInterest() {
  return window['go']['main']['App']['GetTicksOfInterest']();
}

export function GetViewDirection(arg1) {
  return window['go']['main']['App']['GetViewDirection'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WriteBoundary(arg1) {
  return window['go']['main']['App']['WriteBoundary'](arg1);
}
