// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckControlVectors(arg1:number):Promise<boolean>;

export function DefineControlVector(arg1:main.Vector,arg2:number):Promise<void>;

export function GetDemo():Promise<void>;

export function GetPlayerPosition(arg1:main.Player):Promise<main.Point>;

export function GetPlayers(arg1:number):Promise<Array<main.Player>>;

export function GetRayCast(arg1:number):Promise<Array<main.Vector>>;

export function GetTickCount():Promise<number>;

export function GetTicksOfInterest():Promise<Array<number>>;

export function GetViewDirection(arg1:main.Player):Promise<main.Vector>;

export function Greet(arg1:string):Promise<string>;

export function WriteBoundary(arg1:Array<main.Vector>):Promise<void>;
