// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDemo():Promise<void>;

export function GetPlayerPositions(arg1:number):Promise<Array<number>>;

export function GetRayCast(arg1:number):Promise<Array<number>>;

export function GetTickCount():Promise<number>;

export function GetViewDirections(arg1:number):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;

export function WriteBoundary(arg1:Array<number>):Promise<void>;
